Docs/us900203 chap 2 use case
LittleLegend-Pengiun/HK231-thesis pull request #6
Opened 2023-12-09 22:20 UTC by hieuhoang2901

Review :
+ Usecase diagram for whole system (updated follow Mr. Nhan) - chap 3
+ Database diagram for procduct feature (add attributes for entity) - chap 3
+ 6 case study - chap 2
+ UI design by figma - chap 4

Please review and approve

2023-12-10 09:53 UTC, LittleLegend-Pengiun requested changes

2023-12-10 09:53 UTC, LittleLegend-Pengiun commented on test.js
> +function runScript(){
Why do you have this file in the report?

2023-12-11 14:28 UTC, LittleLegend-Pengiun approved these changes

2023-12-11 14:42 UTC, duyphatbk approved these changes

2023-12-11 14:42 UTC, merged